Resources:
  AuroraRdsCluster:
    Type: 'AWS::RDS::DBCluster'
    DeletionPolicy: Delete
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: ${self:custom.database.NAME}
      DatabaseName: ${self:custom.database.NAME}
      Port: ${self:custom.database.PORT}
      EngineVersion: 14.5
      MasterUsername: ${self:custom.database.USER}
      MasterUserPassword: ${self:custom.database.PASSWORD}
      EngineMode: provisioned
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt RDSSecurityGroup.GroupId

  RDSInstance:
    DependsOn: VPCGA
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraRdsCluster
      Engine: aurora-postgresql
      EngineVersion: 14.5
      DBInstanceClass: db.serverless
      PubliclyAccessible: true
      # DBSubnetGroupName: !Ref RDSSubnetGroup
      # VPCSecurityGroups:
      #   - !GetAtt RDSSecurityGroup.GroupId

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'RDS subnet group'
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
      Tags:
        - Key: 'Name'
          Value: 'RDSSubnetGroup'
