service: product

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  profile: serverless
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true

plugins:
  - serverless-webpack

custom:
  webpack:
    packager: 'yarn'

functions:
  product:
    handler: src/index.getProductById
    events:
      - httpApi:
          path: /${self:provider.stage}/products/{id}
          method: get

  products:
    handler: src/index.getProductList
    events:
      - httpApi:
          path: /${self:provider.stage}/products
          method: get
