Resources:
  ImportServiceLambdaS3BucketAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'ImportServiceLambdaS3BucketAccessPolicy'
      Roles: [{ Ref: 'LambdaExecutionRole' }]
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:CopyObject'
              - 's3:GetObjectTagging'
              - 's3:PutObjectTagging'
            Resource:
              - 'Fn::Join':
                  - ''
                  - [{ 'Fn::GetAtt': ['UploadStoreS3Bucket', 'Arn'] }, '/*']
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ImportServiceLambdaExecutionRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Action: 'sts:AssumeRole'
          Principal:
            Service: 'lambda.amazonaws.com'
